### ISSUE TITLE
TypeError: Cannot convert value 0 to a TensorFlow DType.

### ISSUE THREAD

**Issue by Tonto5000** [AastaNV/TRT_object_detection#9]
I tried to convert a SSD mobilenet v1 and got the following error

Using output node NMS
Converting to UFF graph
Warning: No conversion function registered for layer: NMS_TRT yet.
Converting NMS as custom op: NMS_TRT
Warning: No conversion function registered for layer: GridAnchor_TRT yet.
Converting GridAnchor as custom op: GridAnchor_TRT
Warning: No conversion function registered for layer: FlattenConcat_TRT yet.
Converting concat_box_loc as custom op: FlattenConcat_TRT
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    uff_model = uff.from_tensorflow(dynamic_graph.as_graph_def(), model.output_name, output_filename='tmp.uff')
  File "/home/tonto/.virtualenvs/deep_learning/lib/python3.5/site-packages/uff/converters/tensorflow/conversion_helpers.py", line 181, in from_tensorflow
    debug_mode=debug_mode)
  File "/home/tonto/.virtualenvs/deep_learning/lib/python3.5/site-packages/uff/converters/tensorflow/converter.py", line 94, in convert_tf2uff_graph
    uff_graph, input_replacements, debug_mode=debug_mode)
  File "/home/tonto/.virtualenvs/deep_learning/lib/python3.5/site-packages/uff/converters/tensorflow/converter.py", line 79, in convert_tf2uff_node
    op, name, tf_node, inputs, uff_graph, tf_nodes=tf_nodes, debug_mode=debug_mode)
  File "/home/tonto/.virtualenvs/deep_learning/lib/python3.5/site-packages/uff/converters/tensorflow/converter.py", line 47, in convert_layer
    return cls.registry_[op](name, tf_node, inputs, uff_graph, **kwargs)
  File "/home/tonto/.virtualenvs/deep_learning/lib/python3.5/site-packages/uff/converters/tensorflow/converter_functions.py", line 21, in convert_placeholder
    dtype = tf2uff.convert_tf2numpy_dtype(tf_node.attr['dtype'].type)
  File "/home/tonto/.virtualenvs/deep_learning/lib/python3.5/site-packages/uff/converters/tensorflow/converter.py", line 103, in convert_tf2numpy_dtype
    return tf.as_dtype(dtype).as_numpy_dtype
  File "/home/tonto/.virtualenvs/deep_learning/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py", line 719, in as_dtype
    raise TypeError("Cannot convert value %r to a TensorFlow DType." % type_value)
TypeError: Cannot convert value 0 to a TensorFlow DType.

does anyone know what's the issue?

I am using TF-GPU 1.13.1

**Comment by Tonto5000** [comment]
sorry my bad!
forgot to update the node_manipulation.py

**Comment by Tonto5000** [comment]
closed

**Comment by siddas27** [comment]
@Tonto5000 Can you explain what you updated? Coz I am facing the same issue.

**Comment by luckyhacky** [comment]
do the patch on graphsurgeon as explained in readme
